### PR TITLE
#105 ref token

### PR DESCRIPTION
**Pull request by Elochukwu3**
Add refresh token endpoint

### CODE REVIEW

**Review by slimzyBoom — APPROVED** [review]

**Review by slimzyBoom — APPROVED** [review]
Nice feature added

**Review by slimzyBoom — APPROVED** [review]

**Review by slimzyBoom — DISMISSED** [review]

**Review by slimzyBoom — APPROVED** [review]

**Review by slimzyBoom — DISMISSED** [review]

**Review by slimzyBoom — DISMISSED** [review]

**Review by Elochukwu3 — COMMENTED** [review]
All good

**Review by slimzyBoom — APPROVED** [review]
This is good code

**Review by slimzyBoom — APPROVED** [review]
Nice code

**Pull request merged**
